class PRCommentFormatter:
    def fromat_comment(self,report):
        emoji_map = {
            "Critical": "🚨",
            "High": "⚠️",
            "Medium": "🟡",
            "Low": "🟢",
            "Informational": "ℹ️"
        }

        emoji = emoji_map.get(report["severity"], "🔍")

        comment = f"""
## 🛡 CodeSentinel AI Security Report
{emoji} **Severity:** {report['severity']}
📊 **Risk Score:** {report['risk_score']} / 10
🧠 **Confidence:** {round(report['confidence'] * 100, 2)}%


---

### 🔎 Detected Issue
**Type:** {report['label']}

---

### 💡 Recommended Fix
{report['patch']}

---

_This review was automatically generated by CodeSentinel AI._
"""

        return comment